services:
  - type: web
    name: bybit-proxy-free
    plan: free
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    env: node
    envVars:
      - key: NODE_VERSION
        value: 18.x
    healthCheckPath: /health
    autoDeploy: true
